name: TTWO_Baja

on:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minutos
  workflow_dispatch:

jobs:
  ping_repl:
    runs-on: ubuntu-latest
    steps:
      - name: Pingar tu Repl para mantenerlo despierto
        run: |
          curl -I https://TTWOBaja.javier2007mel.repl.co || echo "Error al hacer ping"
